### PR TITLE
[WIP] Support openOrders, cancelOrder, allOrders and get order from Binance…

### PR DESCRIPTION
**Pull request by mbenatti**
… API #19 

The new endpoints are working, because this lib use `doctest Binance` my examples on `binance.ex` are not working, I need help to implement VCR Test's

### CODE REVIEW

**Comment by rupurt** [comment]
@mbenatti I've created a [branch](https://github.com/fremantle-capital/binance.ex/tree/get-open-cancel-all-orders) which has an example of using a cassette on one of the new functions you've added.

@dvcrn I feel like an issue when getting started, is that the config for the package doesn't read the` key` or `secret` from anywhere and it's not clear how to move forward. You requested that I remove something similar to https://github.com/fremantle-capital/binance.ex/commit/8e42f75bd81deb3f8129cf55c8741e24643caa76#diff-de9210b77e43a621a256d7a37fc5f50aL6 in a previous PR. Do you mind adding some documentation around the alternative you want to use instead?

**Comment by dvcrn** [comment]
@rupurt thanks a lot for chiming in and helping with VCR! I was the last week on vacation and didn't have time to take a look yet. 

Yes I didn't want it to by default read the environment variables for this. Especially with generic names like `BINANCE_API_KEY` that the user might already have on his system for other tools. The general idea is that when you actually use this package you would set your own config in your own project, and when you want it to use the env instead of a hard-coded string, you would set that explicitly. 

(By the way, since you're working so much on this these days, I'd love to add you as a contributor if you're interested 👍)

**Comment by rupurt** [comment]
@dvcrn no worries. I'd love to be added as a contributor :) 

How do you feel about adding the following to make it easier for someone to start contributing:

- Add a testing section to the README that describes that you will need to set the values in `config/config.exs`
- Raise an error on startup with a useful message when the api key & signature are `nil` or `""`

**Comment by mbenatti** [comment]
@rupurt What tool do you use to generate exvrc json with request info?

**Comment by rupurt** [comment]
@mbenatti I just run the tests. `use_cassette(...) do` will capture the real HTTP request/response and apply [filters](https://github.com/dvcrn/binance.ex/blob/master/config/config.exs#L9) to scrub sensitive data. If you need to capture a new response you will need to delete the json file and re-run the test.

**Pull request closed without merging**
