### PR TITLE
Add support for FOK & IOC limit orders

### PR DESCRIPTION
**Pull request by rupurt**
Builds upon #14

### CODE REVIEW

**Comment by rupurt** [comment]
@dvcrn this one is now ready that we've merged #14

**Comment by dvcrn** [comment]
Looks good to me! 

What do you think about using constant-like structures for the time in force values? Something like [this](https://elixir-lang.org/getting-started/module-attributes.html#as-constants)

**Comment by rupurt** [comment]
@dvcrn do you mean for the defaults? Do you mind adding an example so I can grok your suggestion a little more.

**Comment by dvcrn** [comment]
I guess not so important right now. I'll merge this first and then we can think about it at a later point 👍

**Pull request merged**
