### PR TITLE
enables the use of per-request api-key/secret-key passing while keeping backward compatibility.

### PR DESCRIPTION
**Pull request by fbettag**
I have used Application.set_env before, but this approach works a lot better.

feedback is welcome.

### CODE REVIEW

**Comment by fbettag** [comment]
gonna rewrite this again

**Comment by dvcrn** [comment]
I think you can inject those as extra optional parameters into `optional_params`, so they are becoming part of the keyword list opts: https://github.com/dvcrn/binance.ex/blob/master/lib/binance.ex#L74

Then inside client, check if those params exist, and if they do use them for overwriting the APplication.get_env stuff

Here's how I did it with a similar library (OpenAI): 

https://github.com/dvcrn/ex_openai/blob/main/lib/ex_openai/client.ex#L117-L118

**Comment by fbettag** [comment]
thanks for the suggestion. currently running trials but iex -S mix looks good

**Comment by fbettag** [comment]
this now is nice and working. sorry for the fuzz

**Review by dvcrn — COMMENTED** [review]
Thanks for the PR! I left some comments, mostly cosmetic 

Also, I think we need a test for this. If you're unsure how to do it, I'm happy to help / take over as well.

**Comment by fbettag** [comment]
Since i really don't know how you like the functions to be, i'd appreciate it if you changed the 3 signatures to your liking :)

I wouldn't be mad if you take over from here, i don't wanna screw around in your awesome code more than needed, but as for the test i suggest using get_account_summary to test this out.

Also, big kudos for the code generator. I've used that part of the library to show off to clients how awesome Elixir can be. ;)

**Comment by fbettag** [comment]
actually trading (buy/sell) seems to be broken with this approach (worked with the other for some weird reason)

**Comment by dvcrn** [comment]
I've changed the function signatures and shuffled things around, then added a test

Could you give this branch a try? https://github.com/dvcrn/binance.ex/pull/107

**Comment by dvcrn** [comment]
Ping :)

**Comment by fbettag** [comment]
sorry i'm currently very busy with pre-christmas work -.- everyone needs stuff launched before christmas

**Comment by fbettag** [comment]
will try to get to it until the weekend

**Comment by fbettag** [comment]
hey dude,

sorry for the delay. so with this branch i get:

```
{:binance_error, %{code: -1104, msg: "Not all sent parameters were read; read '5' parameter(s) but was sent '6'."}}
```

**Comment by dvcrn** [comment]
Thanks for the feedback

hrrrm, which method did you use? Can you post the code?

**Comment by fbettag** [comment]
```binance sell order: {:error,
 {:binance_error,
  %{
    code: -1104,
    msg: "Not all sent parameters were read; read '5' parameter(s) but was sent '6'."
  }}}
[error] [Strategy 2] -- Error placing sell order for 2.27 of SOLBTC at price market: {:binance_error, %{code: -1104, msg: "Not all sent parameters were read; read '5' parameter(s) but was sent '6'."}}
```

```

  def sell(api_key, secret_key, symbol, money, price \\ nil) do
    type = if price == nil, do: "MARKET", else: "LIMIT"
    opts = [qty: money, api_key: api_key, secret_key: secret_key]
    opts = if price != nil, do: Keyword.put(opts, :price, price), else: opts

    Binance.Trade.post_order(symbol, "SELL", type, opts)
    |> IO.inspect(label: "binance sell order")
  end
```

**Comment by fbettag** [comment]
ah damn now i see it

**Pull request merged**
